### ISSUE TITLE
logo 

### ISSUE THREAD

**Issue by jonschlinkert** [here-be/meta#1]
**What is snapdragon?**

Snapdragon is a developer framework for creating "parser-compilers". The technical details are less important. The main concept is that developers can build other tools with Snapdragon, and Snapdragon's plugins can be used like building blocks or puzzle pieces to speed up that process.

**Logo goal**

I'd like a tile, [similar to one of these images](https://www.google.com/search?q=dragon+tile&hl=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiFz6iJt-bXAhWFQyYKHRPKDUgQ_AUICygC&biw=1440&bih=729), but minimalist and a solid color. 

A secondary goal is for the tile to evoke a sense of either a building block or a puzzle piece. This isn't important but would be nice to have.

**Comment by jonschlinkert** [comment]
Examples

![14152467_sqtab](https://user-images.githubusercontent.com/383994/33434359-15596cb8-d5ad-11e7-9e00-538e06de847f.jpeg)
![bc3f5f9e3c2a78274aaebead912db31cf54ecd4c7ba31efdc5b97240ca423805](https://user-images.githubusercontent.com/383994/33434360-156849ea-d5ad-11e7-913b-9de7ae89657c.jpg)
![decorative-blue-glazed-tile-carrying-the-dragon-seal-of-the-chinese-ar7n7k](https://user-images.githubusercontent.com/383994/33434361-159088ce-d5ad-11e7-8d22-48311901c08f.jpg)
![dragon_phoenix_yin_yang_red_and_black_framed_tile](https://user-images.githubusercontent.com/383994/33434362-159f64d4-d5ad-11e7-8e0d-2a8b8d507b47.jpg)
![eafee6e3d506f48151119f55c7a03cd3](https://user-images.githubusercontent.com/383994/33434363-15b0fcda-d5ad-11e7-8bd6-59812e0d980d.jpg)
![red_and_black_dragon_phoenix_yin_yang_ceramic_tile-r0cf819236cb24517ba88e54e97798305_agtk1_8byvr_324](https://user-images.githubusercontent.com/383994/33434364-15c5ec12-d5ad-11e7-8218-ac9b5c1b2bc2.jpg)
![rr13th_century_dragon_tile___peacoquette_designs___copyright_2014_shop_preview](https://user-images.githubusercontent.com/383994/33434365-15e0b4a2-d5ad-11e7-90d9-afcbd10f092e.jpg)
![seal_of_the_dragon_by_balsavor](https://user-images.githubusercontent.com/383994/33434367-15f07f7c-d5ad-11e7-8db4-f366560a747f.jpg)

**Comment by jonschlinkert** [comment]
<h1 align="center"> Concepts </h1>

<h2 align="center"> one </h2>

![1](https://user-images.githubusercontent.com/383994/33620795-e59b3a66-d9b6-11e7-8ab6-ac09ee19009e.jpg)

<br>
<h2 align="center"> two </h2>

![2](https://user-images.githubusercontent.com/383994/33620789-e1280590-d9b6-11e7-87a2-41d2c7b8b0d1.jpg)

<br>
<h2 align="center"> three </h2>

![3](https://user-images.githubusercontent.com/383994/33620804-e9b993e0-d9b6-11e7-985e-b2a2e36b69aa.jpg)

**Comment by doowb** [comment]
I like 1 and 3.
I think 3 a little more because of the dragon head, I don't have a preference between the square or diamond.

**Comment by jonschlinkert** [comment]
# final 

![1-high-resolution-dark-2](https://user-images.githubusercontent.com/383994/33963748-0dd96962-e024-11e7-94f2-7570f66b647b.png)
