### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by FrogTheFrog** [here-be/meta#2]
Hello,

would you consider supporting and maintaining typescript definitions? If needed, I could help you write them.

**Comment by jonschlinkert** [comment]
Yes, that would be great! 

@doowb any objections?

thanks!

**Comment by doowb** [comment]
No objections from me. Thanks!

**Comment by FrogTheFrog** [comment]
@jonschlinkert, @doowb In `utils` there are a lot of functions with wrong/non-existing types. Once I start with PRs could any of you check and correct jsdocs in javascript files (I'm unfamiliar with jsdoc types)? 

For example, I've found a lot of mistakes for return types. I will be reading code itself to determine correct return types.

**Comment by jonschlinkert** [comment]
No problem. FWIW most of the time we don’t actually generate documentation for the utils, we only write code comments for maintenance. But this is a good practice to ensure we pay more attention to the correctness of the comments.

edit: wow, I typed in this reply on my mobile and the autocorrections were terrible.

**Comment by FrogTheFrog** [comment]
What about rewriting everything in typescript? It would be better in the long run. 

The reason I'm suggesting it is because I've noticed that some parts of snapdragon uses ES5 javascript while others use ES6 classes. Thus, I guessed that you're not against new standards, but just do not have enough time. Plus, with typescript you can use decorators which are proposed in ES7!

I would be willing to help you rewrite most of it. Needless to say, if you don't want it, just say no :).

**Comment by jonschlinkert** [comment]
> What about rewriting everything in typescript? It would be better in the long run.

No, I'm really not interested in using typescript. Thank you, though. I'm really only interested in adding typings if it doesn't add any other files (besides the typings) or build steps.

**Comment by FrogTheFrog** [comment]
@jonschlinkert Okay. I'm closing this issue for now and I'll be opening individual PRs. I expect everything to take ~1 week.

**Comment by jonschlinkert** [comment]
> Okay. I'm closing this issue for now and I'll be opening individual PRs. I expect everything to take ~1 week.

No rush! I will be traveling on and off over the next couple of weeks, so I might not be able to merge right away anyway. Thanks again!

**Comment by FrogTheFrog** [comment]
Roger that :) . Anyway, last question. I noticed that most libraries depend on `snapdragon-util: ^1-3.0.x` (not the latest version). Why is it not updated to latest version? Should I update outdated dependencies when I come across them?
